### ISSUE TITLE
Update theme of code snippets

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcallhq.github.io#365]
Update the code snippets to follow the below theme

**Technical Requirements**
- It should look exactly like the screenshot.
- Should produce a minimal amount of changes in this repo.
- It should not affect the page's performance at all.

---

![Code](https://github.com/user-attachments/assets/d102dd95-4df1-4954-816f-87100ae27c50)

**Comment by bnchi** [comment]
/attempt #365

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clyqxeh250002lf09a92s7oo5/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by bnchi** [comment]
I canceled my attempt it took more than I expected, I tried to build a custom theme in prism-react-renderer because I couldn't find an exact match for the requirements in the default themes, but the module doesn't seem to have an option/token for highlighted lines I guess ?!

I tried even the default dark themes and they're giving the current results on my screen :

![Screenshot 2024-07-18 at 12-30-37 GraphQL Configuration Tailcall](https://github.com/user-attachments/assets/a50ebecf-f49f-44c7-9c98-26c745aec750)

**Comment by bnchi** [comment]
> I canceled my attempt it took more than I expected, I tried to build a custom theme in prism-react-renderer because I couldn't find an exact match for the requirements in the default themes, but the module doesn't seem to have an option/token for highlighted lines I guess ?!
> 
> I tried even the default dark themes and they're giving the current results on my screen :


Apparently there's an an override for the  property here if anyone was puzzled https://github.com/tailcallhq/tailcallhq.github.io/blob/develop/src/css/custom.css#L54

**Comment by hunxjunedo** [comment]
/attempt #365

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/hunxjunedo) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @hunxjunedo | &nbsp;&nbsp;&nbsp;2 tailcallhq bounties <br/> + 4 bounties from 2 projects | <div align="center">JavaScript</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clyqxeh250002lf09a92s7oo5/cancel-attempt) |

**Comment by neo773** [comment]
@tusharmath 
Can close this issue as completed.
